### ISSUE TITLE
coco2017数据集问题

### ISSUE THREAD

**Issue by XRONHH** [bubbliiiing/yolo3-pytorch#100]
1、大佬，使用coco2017进行训练，为啥你的准确率mAP0.5可以达到67%左右，但是原文只有55%。是做了进一步的优化呢？
2、请问使用coco2017训练的时候，数据集已经下载好了，应该怎么处理呢？已经使用了qqwweee的yolo3的方法生成了train.txt和val.txt，但是整个目录结构需要怎么设置呢？
3、在使用get_map计算map时，只需要修改map_model  = 4呢？还需要修改什么地方吗？已经下载好pycocotools
感谢大佬解答！

**Comment by bubbliiiing** [comment]
1、原文貌似是test，我这个权重官方转的，训练的时候用了val，所以很高
2、一样的，把train.py里面读取的txt换一下
3、不太行……需要额外的文件，我并没有上传。

**Comment by XRONHH** [comment]
谢谢大佬，第三个问题我也发现了不能直接计算coco训练结果的map，我训练出来的结果在执行时遇到了问题：
Traceback (most recent call last):
  File "E:/yolo_code/yolo3-pytorch/get_map.py", line 114, in <module>
    get_coco_map(class_names = class_names, path = map_out_path)
  File "E:\yolo_code\yolo3-pytorch\utils\utils_map.py", line 899, in get_coco_map
    cocoDt      = cocoGt.loadRes(DR_JSON_PATH)
  File "E:\anaconda3\envs\torch1.2.0\lib\site-packages\pycocotools\coco.py", line 329, in loadRes
    if 'caption' in anns[0]:
IndexError: list index out of range
可能是详细的计算过程我还未能看懂。
如果需要对训练的coco数据集进行map计算，我还需要做哪些工作呢？
感谢大佬解答！十分感谢！！

**Comment by bubbliiiing** [comment]
如果很需要的话留个邮箱，我给你传一个

**Comment by XRONHH** [comment]
谢谢大佬！529948572@qq.com

**Comment by Creep-Dude** [comment]
导师，不知道你还在不在维护这个代码，我很想要coco数据集的评价指标代码，能给我传一个吗，邮箱是q719055169@gmail.com，谢谢导师。

**Comment by bubbliiiing** [comment]
utils_coco= =

**Comment by Creep-Dude** [comment]
> utils_coco= =

是我没认真听课，对不起，下的是去年年底的版本了。

**Comment by bubbliiiing** [comment]
及时pull仓库，不是听课的问题，视频里确实没说这事
