### ISSUE TITLE
 One of the differentiated Tensors does not require grad

### ISSUE THREAD

**Issue by kingrt666666** [bubbliiiing/yolo3-pytorch#110]
想问一下各位，刚刚down下来的模型，在utils_fit.py中加入
grad = torch.autograd.grad(loss_value, model_train.parameters(), retain_graph=True) 
这一句话，为什么会有报错，求不了导呀？是模型在哪里定义一个不用求导的层或者没用的层嘛？

Traceback (most recent call last):
  File "D:/meta_learning/yolo3-pytorch-master/train.py", line 349, in <module>
    fit_one_epoch(model_train, model, yolo_loss, loss_history, optimizer, epoch, epoch_step_meta_train, epoch_step_val, gen_meta_train, gen_val, UnFreeze_Epoch, Cuda, save_period)
  File "D:\meta_learning\yolo3-pytorch-master\utils\utils_fit.py", line 44, in fit_one_epoch
    grad = torch.autograd.grad(loss_value, model_train.parameters(), retain_graph=True)
  File "C:\Program Files\Python37\lib\site-packages\torch\autograd\__init__.py", line 236, in grad
    inputs, allow_unused, accumulate_grad=False)
RuntimeError: One of the differentiated Tensors does not require grad

**Comment by bubbliiiing** [comment]
-不太懂…我这里没有，是不是环境问题呢
