### ISSUE TITLE
把giou设置为False，训练出错，提示不匹配信息

### ISSUE THREAD

**Issue by JohnFiv** [bubbliiiing/yolo3-pytorch#113]

**Comment by JohnFiv** [comment]
![Uploading 捕获.PNG…]()

**Comment by JohnFiv** [comment]
loss_x = torch.mean(self.BCELoss(x[obj_mask], y_true[..., 0][obj_mask]) * box_loss_scale)
RuntimeError: The size of tensor a (5) must match the size of tensor b (13) at non-singleton dimension 3

**Comment by JohnFiv** [comment]
Traceback (most recent call last):
  File "D:\Pytorch_workspace\yolo3-pytorch-master_1\utils\utils_fit.py", line 42, in fit_one_epoch
    loss_item = yolo_loss(l, outputs[l], targets)
  File "D:\ProgramData\Anaconda3\envs\pytorch\lib\site-packages\torch\nn\modules\module.py", line 547, in __call__
    result = self.forward(*input, **kwargs)
  File "D:\Pytorch_workspace\yolo3-pytorch-master_1\nets\yolo_training.py", line 192, in forward
    loss_x = torch.mean(self.BCELoss(x[obj_mask], y_true[..., 0][obj_mask]) * box_loss_scale)
RuntimeError: The size of tensor a (2) must match the size of tensor b (13) at non-singleton dimension 3

**Comment by JohnFiv** [comment]
最后一句，The size of tensor a（2）这段话每次报错都不同，有时候是a（4），a（6），，，

**Comment by bubbliiiing** [comment]
box_loss_scale也要加个[obj_mask]
