### ISSUE TITLE
当我运行 train.py 报错AttributeError: 'DarkNet' object has no attribute 'layers_out_filters'

### ISSUE THREAD

**Issue by hapizuoyou** [bubbliiiing/yolo3-pytorch#129]
没找到问题是什么呀 ：（

**Comment by hapizuoyou** [comment]
Traceback (most recent call last):
  File "D:/program/yolo3-pytorch-now-use/train.py", line 248, in <module>
    model = YoloBody(anchors_mask, num_classes, pretrained=pretrained)
  File "D:program\yolo3-pytorch-now-use\nets\yolo.py", line 70, in __init__
    out_filters = self.backbone.layers_out_filters
  File "D:\envs\yolo3-pytorch\lib\site-packages\torch\nn\modules\module.py", line 1185, in __getattr__
    raise AttributeError("'{}' object has no attribute '{}'".format(
AttributeError: 'DarkNet' object has no attribute 'layers_out_filters'

**Comment by bubbliiiing** [comment]
你自己改了什么呢。我看是有这个layers_out_filters 的
