### ISSUE TITLE
Python 递归错误RecursionError: maximum recursion depth exceeded

### ISSUE THREAD

**Issue by dengxiongshi** [bubbliiiing/yolo3-pytorch#141]
运行train.py时出现RecursionError: maximum recursion depth ，按照网上的修改
import sys
sys.setrecursionlimit(100000) #设置递归深度
也没用

`Traceback (most recent call last):
  File "D:\Anaconda3\envs\py36\lib\code.py", line 91, in runcode
    exec(code, self.locals)
  File "<input>", line 1, in <module>
  File "D:\Program Files\JetBrains\PyCharm Community Edition 2022.1.1\plugins\python-ce\helpers\pydev\_pydev_bundle\pydev_umd.py", line 198, in runfile
    pydev_imports.execfile(filename, global_vars, local_vars)  # execute the script
  File "D:\Program Files\JetBrains\PyCharm Community Edition 2022.1.1\plugins\python-ce\helpers\pydev\_pydev_imps\_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "D:/python_code/yolo3-pytorch/train.py", line 20, in <module>
    from utils.callbacks import LossHistory, EvalCallback
  File "D:\Program Files\JetBrains\PyCharm Community Edition 2022.1.1\plugins\python-ce\helpers\pydev\_pydev_bundle\pydev_import_hook.py", line 21, in do_import
    module = self._system_import(name, *args, **kwargs)
  File "D:\python_code\yolo3-pytorch\utils\callbacks.py", line 18, in <module>
    from .utils_map import get_coco_map, get_map
  File "D:\Program Files\JetBrains\PyCharm Community Edition 2022.1.1\plugins\python-ce\helpers\pydev\_pydev_bundle\pydev_import_hook.py", line 21, in do_import
    module = self._system_import(name, *args, **kwargs)
  File "D:\python_code\yolo3-pytorch\utils\utils_map.py", line 15, in <module>
    matplotlib.use('Agg')
  File "D:\Program Files\JetBrains\PyCharm Community Edition 2022.1.1\plugins\python-ce\helpers\pydev\pydev_ipython\matplotlibtools.py", line 70, in patched_use
    matplotlib.real_use(*args, **kwargs)
  File "D:\Program Files\JetBrains\PyCharm Community Edition 2022.1.1\plugins\python-ce\helpers\pydev\pydev_ipython\matplotlibtools.py", line 70, in patched_use
    matplotlib.real_use(*args, **kwargs)
  File "D:\Program Files\JetBrains\PyCharm Community Edition 2022.1.1\plugins\python-ce\helpers\pydev\pydev_ipython\matplotlibtools.py", line 70, in patched_use
    matplotlib.real_use(*args, **kwargs)
  [Previous line repeated 481 more times]
RecursionError: maximum recursion depth exceeded
`

**Comment by bubbliiiing** [comment]
什么版本？我没见过这个错误，蛮奇怪

**Comment by dengxiongshi** [comment]
**Python 3.7下面是安装的包**
Package                 Version
----------------------- ------------
absl-py                 1.1.0
cachetools              5.2.0
certifi                 2022.6.15
charset-normalizer      2.1.0
cycler                  0.11.0
google-auth             2.9.0
google-auth-oauthlib    0.4.6
grpcio                  1.47.0
h5py                    2.10.0
idna                    3.3
importlib-metadata      4.12.0
kiwisolver              1.4.3
Markdown                3.3.7
matplotlib              3.1.2
numpy                   1.21.6
oauthlib                3.2.0
opencv-python           4.1.2.30
Pillow                  9.2.0
pip                     22.1.2
protobuf                3.19.4
pyasn1                  0.4.8
pyasn1-modules          0.2.8
pyparsing               3.0.9
python-dateutil         2.8.2
requests                2.28.1
requests-oauthlib       1.3.1
rsa                     4.8
scipy                   1.7.3
setuptools              61.2.0
six                     1.16.0
tensorboard             2.9.1
tensorboard-data-server 0.6.1
tensorboard-plugin-wit  1.8.1
torch                   1.11.0+cu115
torchvision             0.12.0+cu115
tqdm                    4.60.0
typing_extensions       4.3.0
urllib3                 1.26.10
Werkzeug                2.1.2
wheel                   0.37.1
wincertstore            0.2
zipp                    3.8.0

**Comment by bubbliiiing** [comment]
也许该试试低版本，你B站也问了吧，也可能是内存不足

**Comment by bubbliiiing** [comment]
这……可能没保存😂
