### ISSUE TITLE
运行train.py始终显示无法识别tensorboard模块

### ISSUE THREAD

**Issue by JinYuAFei** [bubbliiiing/yolo3-pytorch#143]
安装上tensorboard且版本没问题情况下一直显示ModuleNotFoundError: No module named 'tensorboard'

**Comment by JinYuAFei** [comment]
报一下错误 Traceback (most recent call last):
  File "D:\Anaconda\envs\pytorch\lib\site-packages\torch\utils\tensorboard\__init__.py", line 2, in <module>
    from torch.utils.tensorboard.summary.writer.record_writer import RecordWriter  # noqa F401
  File "D:\Anaconda\envs\pytorch\lib\site-packages\torch\utils\tensorboard\summary.py", line 14, in <module>     
    from utils.callbacks import LossHistory, EvalCallback
  File "d:\yolo3-pytorch-master\yolo3-pytorch-master\utils\callbacks.py", line 9, in <module>
    from torch.utils.tensorboard import SummaryWriter
  File "D:\Anaconda\envs\pytorch\lib\site-packages\torch\utils\tensorboard\__init__.py", line 4, in <module>     
    raise ImportError('TensorBoard logging requires TensorBoard with Python summary writer installed. '
ImportError: TensorBoard logging requires TensorBoard with Python summary writer installed. This should be available in 1.14 or above.

**Comment by bubbliiiing** [comment]
你没有激活环境装

**Comment by JinYuAFei** [comment]
> 你没有激活环境装

已解决，谢谢啦

**Comment by ZhangJiaRed** [comment]
> > 你没有激活环境装
> 
> 已解决，谢谢啦

请问你是如何解决的，是在环境中直接conda install tensorboard就行了吗
