### ISSUE TITLE
训练问题，求大佬指教

### ISSUE THREAD

**Issue by QCFY666888** [bubbliiiing/yolo3-pytorch#92]
Traceback (most recent call last):
  File "C:/Users/Bright Rich/Desktop/研究方向/yolo3-pytorch-master/train.py", line 193, in <module>
    epoch_step, epoch_step_val, gen, gen_val, end_epoch, Cuda)
  File "C:\Users\Bright Rich\Desktop\研究方向\yolo3-pytorch-master\utils\utils_fit.py", line 13, in fit_one_epoch
    for iteration, batch in enumerate(gen):
  File "D:\Program Files (x86)\Anaconda3\lib\site-packages\torch\utils\data\dataloader.py", line 435, in __next__
    data = self._next_data()
  File "D:\Program Files (x86)\Anaconda3\lib\site-packages\torch\utils\data\dataloader.py", line 1085, in _next_data
    return self._process_data(data)
  File "D:\Program Files (x86)\Anaconda3\lib\site-packages\torch\utils\data\dataloader.py", line 1111, in _process_data
    data.reraise()
  File "D:\Program Files (x86)\Anaconda3\lib\site-packages\torch\_utils.py", line 428, in reraise
    raise self.exc_type(msg)
FileNotFoundError: Caught FileNotFoundError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "D:\Program Files (x86)\Anaconda3\lib\site-packages\torch\utils\data\_utils\worker.py", line 198, in _worker_loop
    data = fetcher.fetch(index)
  File "D:\Program Files (x86)\Anaconda3\lib\site-packages\torch\utils\data\_utils\fetch.py", line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "D:\Program Files (x86)\Anaconda3\lib\site-packages\torch\utils\data\_utils\fetch.py", line 44, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "C:\Users\Bright Rich\Desktop\研究方向\yolo3-pytorch-master\utils\dataloader.py", line 27, in __getitem__
    image, box  = self.get_random_data(self.annotation_lines[index], self.input_shape[0:2], random = self.train)
  File "C:\Users\Bright Rich\Desktop\研究方向\yolo3-pytorch-master\utils\dataloader.py", line 46, in get_random_data
    image   = Image.open(line[0])
  File "D:\Program Files (x86)\Anaconda3\lib\site-packages\PIL\Image.py", line 2809, in open
    fp = builtins.open(filename, "rb")
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\Bright'

**Comment by QCFY666888** [comment]
我已经检查过文件的相对路径和根目录，都没啥问题，不知道问题到底出在哪

**Comment by sammyxiong** [comment]
检查下C:\Users\Bright这个路径
















At 2021-11-16 10:17:06, "QCFY666888" ***@***.***> wrote:

Traceback (most recent call last):
File "C:/Users/Bright Rich/Desktop/研究方向/yolo3-pytorch-master/train.py", line 193, in
epoch_step, epoch_step_val, gen, gen_val, end_epoch, Cuda)
File "C:\Users\Bright Rich\Desktop\研究方向\yolo3-pytorch-master\utils\utils_fit.py", line 13, in fit_one_epoch
for iteration, batch in enumerate(gen):
File "D:\Program Files (x86)\Anaconda3\lib\site-packages\torch\utils\data\dataloader.py", line 435, in next
data = self._next_data()
File "D:\Program Files (x86)\Anaconda3\lib\site-packages\torch\utils\data\dataloader.py", line 1085, in _next_data
return self._process_data(data)
File "D:\Program Files (x86)\Anaconda3\lib\site-packages\torch\utils\data\dataloader.py", line 1111, in _process_data
data.reraise()
File "D:\Program Files (x86)\Anaconda3\lib\site-packages\torch_utils.py", line 428, in reraise
raise self.exc_type(msg)
FileNotFoundError: Caught FileNotFoundError in DataLoader worker process 0.
Original Traceback (most recent call last):
File "D:\Program Files (x86)\Anaconda3\lib\site-packages\torch\utils\data_utils\worker.py", line 198, in _worker_loop
data = fetcher.fetch(index)
File "D:\Program Files (x86)\Anaconda3\lib\site-packages\torch\utils\data_utils\fetch.py", line 44, in fetch
data = [self.dataset[idx] for idx in possibly_batched_index]
File "D:\Program Files (x86)\Anaconda3\lib\site-packages\torch\utils\data_utils\fetch.py", line 44, in
data = [self.dataset[idx] for idx in possibly_batched_index]
File "C:\Users\Bright Rich\Desktop\研究方向\yolo3-pytorch-master\utils\dataloader.py", line 27, in getitem
image, box = self.get_random_data(self.annotation_lines[index], self.input_shape[0:2], random = self.train)
File "C:\Users\Bright Rich\Desktop\研究方向\yolo3-pytorch-master\utils\dataloader.py", line 46, in get_random_data
image = Image.open(line[0])
File "D:\Program Files (x86)\Anaconda3\lib\site-packages\PIL\Image.py", line 2809, in open
fp = builtins.open(filename, "rb")
FileNotFoundError: [Errno 2] No such file or directory: 'C:\Users\Bright'

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by sammyxiong** [comment]
C:\Users\Bright Rich
去掉这个路径的的空格？



|
熊向明
***@***.***
|
发自 网易邮箱大师




---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2021年11月16日 10:19 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***> |
| 主题 | Re: [bubbliiiing/yolo3-pytorch] 训练问题，求大佬指教 (Issue #92) |

我已经检查过文件的相对路径和根目录，都没啥问题，不知道问题到底出在哪

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by QCFY666888** [comment]
已解决，是空格的原因导致的，感谢
