### ISSUE TITLE
权值文件损坏，换权值文件出现如下问题

### ISSUE THREAD

**Issue by cjr13018** [bubbliiiing/yolo3-pytorch#97]
root@61aae8b118ea1f789e385870:/user-data/yolo3-pytorch-ours# python train.py
initialize network with normal type
Load weights /user-data/yolo3-pytorch-ours/model_data/yolov3_d53_mstrain-416_273e_coco-2b60fcd9.pth.
Traceback (most recent call last):
  File "train.py", line 135, in <module>
    pretrained_dict = {k: v for k, v in pretrained_dict.items() if np.shape(model_dict[k]) == np.shape(v)}
  File "train.py", line 135, in <dictcomp>
    pretrained_dict = {k: v for k, v in pretrained_dict.items() if np.shape(model_dict[k]) == np.shape(v)}
KeyError: 'meta'
root@61aae8b118ea1f789e385870:/user-data/yolo3-pytorch-ours#

**Comment by bubbliiiing** [comment]
这不是我提供的权值=
