### ISSUE TITLE
分类可以设置为空吗?

### ISSUE THREAD

**Issue by ma062304** [bubbliiiing/yolo3-pytorch#98]
我的实际运用不需要输出种类，可以把model_data中的coco classes和voc classes里的分类清空吗？

**Comment by ma062304** [comment]
分类文件夹清空后预测显示这个：
D:\anaconda\python.exe D:/abc/yolo1/predict.py
logs/ep100-loss0.003-val_loss0.003.pth model, anchors, and classes loaded.
Input image filename:D:\abc\yolo1\VOCdevkit\VOC2007\JPEGImages\000039.JPG
Traceback (most recent call last):
  File "D:/abc/yolo1/predict.py", line 65, in <module>
    r_image = yolo.detect_image(image)
  File "D:\abc\yolo1\yolo.py", line 136, in detect_image
    outputs = self.bbox_util.decode_box(outputs)
  File "D:\abc\yolo1\utils\utils_bbox.py", line 109, in decode_box
    conf.view(batch_size, -1, 1), pred_cls.view(batch_size, -1, self.num_classes)), -1)
RuntimeError: cannot reshape tensor of 0 elements into shape [1, -1, 0] because the unspecified dimension size -1 can be any value and is ambiguous

**Comment by bubbliiiing** [comment]
不可以清空……我建议你看看代码再去掉种类吧

**Comment by bubbliiiing** [comment]
看看预测过程的代码
